inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

inherit_gem:
  prettier: rubocop.yml

require: 
  - rubocop-performance

AllCops:
  NewCops: enable
  DisplayStyleGuide: true
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'
    - 'vendor/bundle'
    - '*.gemspec'
